template = "https://github.com/giellalt/template-lang-und"
rev_id = 213
template_sha = "578d8bbf67a7070b578ed5ce3ac848f5411ce184"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-bwi"
__UND2C__ = "bwi"
__UNDEFINED__ = "Baniwa"
__UND__ = "bwi"
