template = "https://github.com/giellalt/template-lang-und"
rev_id = 218
template_sha = "f977f8caf5d82030f9681fa655ea0cb16b83f5de"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-bwi"
__UND2C__ = "bwi"
__UNDEFINED__ = "Baniwa"
__UND__ = "bwi"
