template = "https://github.com/giellalt/template-lang-und"
rev_id = 223
template_sha = "f4ae0ba4a15c7ca7b0dbbb23cdf12355758920b4"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-bwi"
__UND2C__ = "bwi"
__UNDEFINED__ = "Baniwa"
__UND__ = "bwi"
